### ISSUE TITLE
Odstranit vypis sql query pri CSV loade a vypis poli. bod11/admin.php

### ISSUE THREAD

**Issue by shneeder** [shneeder/wt2-skuska#9]

**Comment by KamilBT** [comment]
inak sql query tam nemo co vypisovat, iba errory a to pole som uz zakomentoval

**Comment by shneeder** [comment]
Ja som tam zabudol kontrolny vypis, ked som si hladal chybu, dal som to sem iba aby sa na to nezabudlo.

**Comment by shneeder** [comment]
done
